// examples/vue-demo/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import { RasediClient, Gateway } from "rasedi-sdk";

const output = ref("Click button to start test");

const secretKey =
  "live_laisvaY9wQA56WI1vQQc3IR8xAF7QKgtVOfOpt9X-VAMTKXMk3QeN8qjXjYSqxgHuqbS0CQlUUDbeamHZUWL632HJTI2-9";
const privateKey = `-----BEGIN PRIVATE KEY-----
MC4CAQAwBQYDK2VwBCIEIIXCDtl2pujtCSajfQHrRMqrpExijGhuh2fvmIgrI/t+W87
-----END PRIVATE KEY-----`;

const runTest = async () => {
  output.value = "Initializing Client...";
  try {
    const client = new RasediClient(privateKey, secretKey);
    output.value += "\nCreating Payment...";

    const payment = await client.createPayment({
      amount: "10500",
      title: "Test VueJS SDK",
      description: "Testing Universal JS SDK",
      gateways: [Gateway.CREDIT_CARD],
      redirectUrl: "https://example.com/callback",
      callbackUrl: "https://example.com/webhook",
      collectFeeFromCustomer: true,
      collectCustomerEmail: true,
      collectCustomerPhoneNumber: false,
    });

    output.value += `\nPayment Created: ${payment.body.referenceCode}\nStatus: ${payment.body.status}`;

    if (payment.body.referenceCode) {
      output.value += "\nFetching Payment...";
      const details = await client.getPaymentByReference(
        payment.body.referenceCode,
      );
      output.value += `\nFetched Status: ${details.body.status}`;
      if (details.body.history && details.body.history.length > 0) {
        output.value += `\nHistory Items: ${details.body.history.length}`;
        details.body.history.forEach((item: any) => {
          output.value += `\n  - ${item.status} via ${item.gateway}`;
        });
      }

      output.value += "\nCancelling Payment...";
      const ignored = await client.cancelPayment(payment.body.referenceCode);
      output.value += `\nCancelled Status: ${ignored.body.status}`;
    }
  } catch (error: any) {
    console.error(error);
    output.value += `\nError: ${error.message || error}`;
    if (error.response) {
      output.value += `\nResponse Data: ${JSON.stringify(error.response.data)}`;
    }
  }
};
</script>

<template>
  <div style="padding: 20px">
    <h1>Rasedi SDK Vue Test</h1>
    <button @click="runTest">Run SDK Test</button>
    <pre
      style="
        margin-top: 20px;
        background: #333;
        color: #fff;
        padding: 10px;
        border-radius: 5px;
        white-space: pre-wrap;
        text-align: left;
      "
      >{{ output }}</pre
    >
  </div>
</template>

// examples/react-demo/src/App.tsx
import { useState } from 'react';
import { RasediClient, Gateway } from 'rasedi-sdk';

const secretKey =
  "live_laisvaY9wQA56WI1vQQc3IR8xAF7QKgtVOfOpt9X-VAMTKXMk3QeN8qjXjYSqxgHuqbS0CQlUUDbeamHZUWL632HJTI2-9";
const privateKey = `-----BEGIN PRIVATE KEY-----
MC4CAQAwBQYDK2VwBCIEIIXCDtl2pujtCSajfQHrRMqrpExijGhuh2fvmIgrI/t+W87
-----END PRIVATE KEY-----`;

function App() {
  const [output, setOutput] = useState<string>('Click button to start test');

  const runTest = async () => {
    setOutput('Initializing Client...');
    try {
        const client = new RasediClient(privateKey, secretKey);
        setOutput(prev => prev + '\nCreating Payment...');

        const payment = await client.createPayment({
            amount: "10500",
            title: "Test JS SDK",
            description: "Testing Universal JS SDK",
            gateways: [Gateway.CREDIT_CARD],
            redirectUrl: "https://example.com/callback",
            callbackUrl: "https://example.com/webhook",
            collectFeeFromCustomer: true,
            collectCustomerEmail: true,
            collectCustomerPhoneNumber: false,
        });

        setOutput(prev => prev + `\nPayment Created: ${payment.body.referenceCode}\nStatus: ${payment.body.status}`);

        if (payment.body.referenceCode) {
            setOutput(prev => prev + '\nFetching Payment...');
            const details = await client.getPaymentByReference(payment.body.referenceCode);
            setOutput(prev => prev + `\nFetched Status: ${details.body.status}`);
            if (details.body.history && details.body.history.length > 0) {
                setOutput(prev => prev + `\nHistory Items: ${details.body.history.length}`);
                details.body.history.forEach(item => {
                    setOutput(prev => prev + `\n  - ${item.status} via ${item.gateway}`);
                });
            }

             setOutput(prev => prev + '\nCancelling Payment...');
            const ignored = await client.cancelPayment(payment.body.referenceCode);
            setOutput(prev => prev + `\nCancelled Status: ${ignored.body.status}`);
        }

    } catch (error: any) {
        console.error(error);
        setOutput(prev => prev + `\nError: ${error.message || error}`);
        if (error.response) {
            setOutput(prev => prev + `\nResponse Data: ${JSON.stringify(error.response.data)}`);
        }
    }
  };

  return (
    <div style={{ padding: 20 }}>
      <h1>Rasedi SDK Test</h1>
      <button onClick={runTest}>Run SDK Test</button>
      <pre style={{ marginTop: 20, background: '#333', color: '#fff', padding: 10, borderRadius: 5, whiteSpace: 'pre-wrap', textAlign: 'left' }}>
        {output}
      </pre>
    </div>
  )
}

export default App
